using Patterns_And_Principles.Patterns.The_State_Pattern.Script._02_RealWorldUsage.Manager;
using UnityEngine;

namespace Patterns_And_Principles.Patterns.The_State_Pattern.Script._02_RealWorldUsage.State
{
    public class AppleChewedState : AppleBaseState
    {
        public override void EnterState(AppleStateManager appleStateManager)
        {
            Debug.Log("Entered AppleChewedState"); 
            MeshRenderer renderer = appleStateManager.GetComponent<MeshRenderer>();
            renderer.material.color = new Color(0f, .25f, 0f);
            appleStateManager.transform.localScale = new Vector3(0.8f, 0.7f, 0.8f);
            appleStateManager.transform.Rotate(10f, 0f, 0f);
            
        }

        public override void UpdateState(AppleStateManager appleStateManager)
        {
            
        }

        public override void OnCollisionEnter(AppleStateManager appleStateManager,  Collision collision)
        {
            
        }
    }
}