using Patterns_And_Principles.Patterns.The_State_Pattern.Script._02_RealWorldUsage.Manager;
using UnityEngine;

namespace Patterns_And_Principles.Patterns.The_State_Pattern.Script._02_RealWorldUsage.State
{
    public class AppleRottenState : AppleBaseState
    {
        public override void EnterState(AppleStateManager appleStateManager)
        {
            Debug.Log("Entered AppleRottenState");
            appleStateManager.GetComponent<MeshRenderer>().materials[0].color = Color.gray;
        }

        public override void UpdateState(AppleStateManager appleStateManager)
        {
            
        }

        public override void OnCollisionEnter(AppleStateManager appleStateManager, Collision collision)
        {
            
        }
    }
}